const architecture_projects = [
  {
    projectId: "BCN44",
    projectDescription: "",
    data: [
      {
        imageId: "BCN441",
        title: "BCN44 - HOUSE",
        year: 2022,
        location: "Sant Antoni de Vilamajor, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BCN44/E32_BCN44HOUSE (1).jpg"),
        isLandscape: true,
        text: "The intention of this project is to play with precise geometries and modern minimalist styles, in order to create a modern harmony of great elegance between inside and outside. Following a linear geometry, we were able to create a clean and defined space, capable of transmitting peacefulness and elegance.",
      },
      {
        imageId: "BCN442",
        title: "BCN44 - HOUSE",
        year: 2022,
        location: "Sant Antoni de Vilamajor, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BCN44/E32_BCN44HOUSE (2).jpg"),
        isLandscape: true,
        text: "The entire program of this house is arranged on three rectangular pieces on the ground floor. A solution of internal continuity that gives life to space distinct from rigorous geometric shapes.",
      },
      {
        imageId: "BCN443",
        title: "BCN44 - HOUSE",
        year: 2022,
        location: "Sant Antoni de Vilamajor, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BCN44/E32_BCN44HOUSE (3).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "BCN444",
        title: "BCN44 - HOUSE",
        year: 2022,
        location: "Sant Antoni de Vilamajor, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BCN44/E32_BCN44HOUSE (4).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "BCN445",
        title: "BCN44 - HOUSE",
        year: 2022,
        location: "Sant Antoni de Vilamajor, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BCN44/E32_BCN44HOUSE (5).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "BCN446",
        title: "BCN44 - HOUSE",
        year: 2022,
        location: "Sant Antoni de Vilamajor, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BCN44/E32_BCN44HOUSE (6).jpg"),
        isLandscape: true,
        text: "",
      },
    ],
  },  
  {
    projectId: "BDN07",
    projectDescription: "",
    data: [
      {
        imageId: "BDN071",
        title: "BDN07 - HOUSE",
        year: 2022,
        location: "Badalona, Spain",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BDN07/E32_BDN07HOUSE (1).jpg"),
        isLandscape: false,
        text: "Building a house between partitions is one of the most common cases, especially in an urban environment. Due to the restrictions of the plot, it is not always possible to have the best possible orientation. The introduction of patios is always a very interesting strategy due to its bioclimatic benefits.",
      },
      {
        imageId: "BDN072",
        title: "BDN07 - HOUSE",
        year: 2022,
        location: "Badalona, Spain",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BDN07/E32_BDN07HOUSE (2).jpg"),
        isLandscape: true,
        text: "The rectangular layout of the building allows to create an interior patio to enhance the relationship with natural lighting and ensure good natural ventilation in all parts of the house.",
      },
      {
        imageId: "BDN073",
        title: "BDN07 - HOUSE",
        year: 2022,
        location: "Badalona, Spain",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BDN07/E32_BDN07HOUSE (3).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "BDN074",
        title: "BDN07 - HOUSE",
        year: 2022,
        location: "Badalona, Spain",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BDN07/E32_BDN07HOUSE (4).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "BDN075",
        title: "BDN07 - HOUSE",
        year: 2022,
        location: "Badalona, Spain",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BDN07/E32_BDN07HOUSE (5).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "BDN076",
        title: "BDN07 - HOUSE",
        year: 2022,
        location: "Badalona, Spain",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/BDN07/E32_BDN07HOUSE (6).jpg"),
        isLandscape: true,
        text: "",
      },
    ],
  },
  {
    projectId: "CAB05",
    projectDescription: "",
    data: [
      {
        imageId: "CAB051",
        title: "CAB05 - HOUSE",
        year: 2022,
        location: "Cabrils, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/CAB05/E32_CAB05HOUSE (1).jpg"),
        isLandscape: true,
        text: "Architecture allows to balance the energies of a home so that its inhabitants feel good and in harmony with the place they occupy. This is carried out with the observation of the surrounding, the environment and the flow of energy that circulates through the spaces in which we live.",
      },
      {
        imageId: "CAB052",
        title: "CAB05 - HOUSE",
        year: 2022,
        location: "Cabrils, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/CAB05/E32_CAB05HOUSE (2).jpg"),
        isLandscape: true,
        text: "The Feng Shui philosophy seeks to harmonize the energy that flows in the environment with the spaces, thus benefiting the health, well-being and prosperity of the occupants. Its rules seek to recreate in the place of life or work, the perfect harmony that nature offers us.",
      },
      {
        imageId: "CAB053",
        title: "CAB05 - HOUSE",
        year: 2022,
        location: "Cabrils, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/CAB05/E32_CAB05HOUSE (3).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "CAB054",
        title: "CAB05 - HOUSE",
        year: 2022,
        location: "Cabrils, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/CAB05/E32_CAB05HOUSE (4).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "CAB055",
        title: "CAB05 - HOUSE",
        year: 2022,
        location: "Cabrils, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/CAB05/E32_CAB05HOUSE (5).jpg"),
        isLandscape: true,
        text: "",
      },
    ],
  },
  {
    projectId: "PRS292",
    projectDescription: "",
    data: [
      {
        imageId: "PRS2921",
        title: "PRS292 - HOUSE",
        year: 2022,
        location: "Prats i Sansors, Lleida",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/PRS292/E32_PRS292HOUSE (1).jpg"),
        isLandscape: true,
        text: "The word architecture encompasses many meanings. For us, architecture marks the lifestyle, the comfort of the people, the day to day, the way people live, even the culture that is part of acquiring this knowledge.",
      },
      {
        imageId: "PRS2922",
        title: "PRS292 - HOUSE",
        year: 2022,
        location: "Prats i Sansors, Lleida",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/PRS292/E32_PRS292HOUSE (2).jpg"),
        isLandscape: true,
        text: "The first thing is to understand the environment: not only in the physical sense, but also the cultural, social, urban one in order to give the best that would fit in this place depending on what is needed. ",
      },
    ],
  },
  {
    projectId: "BCN017",
    projectDescription: "",
    data: [
      {
        imageId: "SANTS1",
        title: "BCN017 - SANTS",
        year: 2021,
        location: "Sants-Montjuïc, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/09.Sants/Sants01.jpg"),
        isSmallThumbnail: true,
        text: "As architecture experts, we are responsible for raising awareness and protecting the cultural and historical legacy of identity. The enhancement of existing elements is a fundamental part of the project whenever possible.",
      },
      {
        imageId: "SANTS2",
        title: "BCN017 - SANTS",
        year: 2021,
        location: "Sants-Montjuïc, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/09.Sants/Sants02.jpg"),
        isSpecialPortrait: true,
        text: "",
      },
      {
        imageId: "SANTS3",
        title: "BCN017 - SANTS",
        year: 2021,
        location: "Sants-Montjuïc, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/09.Sants/Sants03.jpg"),
        isSpecialLandscape: true,
        text: "Using traditional Barcelona mosaic floors to embellish the kitchen, while the continuity of the oak parquet is interrupted by colorful mosaic motifs, is a perfect example. Likewise, the green of the plants establishes a dialogue in harmony with nature.",
      },
      {
        imageId: "SANTS4",
        title: "BCN017 - SANTS",
        year: 2021,
        location: "Sants-Montjuïc, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/09.Sants/Sants04.jpg"),
        isSpecialLandscape: true,
        text: "",
      },
      {
        imageId: "SANTS5",
        title: "BCN017 - SANTS",
        year: 2021,
        location: "Sants-Montjuïc, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/09.Sants/Sants05.jpg"),
        isSpecialPortrait: true,
        text: "",
      },
      {
        imageId: "SANTS6",
        title: "BCN017 - SANTS",
        year: 2021,
        location: "Sants-Montjuïc, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/09.Sants/Sants06.jpg"),
        isSpecialPortrait: true,
        text: "",
      },
    ],
  },
  {
    projectId: "BCN326",
    projectDescription: "",
    data: [
      {
        imageId: "PROVENCA1",
        title: "BCN032 - PROVENÇA",
        year: 2021,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/010.Provenca/Provenca01.jpg"),
        isThumbnail: true,
        text: "Designed in the early 1900s, this apartment on Calle Provença respond to the elegant geometric decorations that refer to Catalan Modernist Architecture. The essence of this project has been to recover and complete the existing mosaic with the utmost respect, preserving the originality and beauty of such an important piece for Catalan culture.",
      },
      {
        imageId: "PROVENCA2",
        title: "BCN032 - PROVENÇA",
        year: 2021,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/010.Provenca/Provenca02.jpg"),
        isSpecialLandscape: true,
        text: "",
      },
      {
        imageId: "PROVENCA3",
        title: "BCN032 - PROVENÇA",
        year: 2021,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/010.Provenca/Provenca03.jpg"),
        isSpecialPortrait: true,
        text: "The hydraulic mosaic is a type of pavement made with cement tiles that, depending on the different artistic designs and their placement, can form decorative motifs of great beauty and different styles, from the simplest with few elements to the most elaborate with a profusion of shapes and colors.",
      },
      {
        imageId: "PROVENCA4",
        title: "BCN032 - PROVENÇA",
        year: 2021,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/010.Provenca/Provenca04.jpg"),
        isSpecialPortrait: true,
        text: "",
      },
      {
        imageId: "PROVENCA5",
        title: "BCN032 - PROVENÇA",
        year: 2021,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/010.Provenca/Provenca05.jpg"),
        isLargeThumbnail: true,
        text: "",
      },
      {
        imageId: "PROVENCA6",
        title: "BCN032 - PROVENÇA",
        year: 2021,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/010.Provenca/Provenca06.jpg"),
        isSpecialLandscape: true,
        text: "",
      },
      {
        imageId: "PROVENCA7",
        title: "BCN032 - PROVENÇA",
        year: 2021,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/010.Provenca/Provenca07.jpg"),
        isSpecialPortrait: true,
        text: "",
      },
      {
        imageId: "PROVENCA8",
        title: "BCN032 - PROVENÇA",
        year: 2021,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/010.Provenca/Provenca08.jpg"),
        isMediumThumbnail: true,
        text: "",
      },
      {
        imageId: "PROVENCA9",
        title: "BCN032 - PROVENÇA",
        year: 2021,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/010.Provenca/Provenca09.jpg"),
        isSpecialLandscape: true,
        text: "",
      },
    ],
  },
  {
    projectId: "BCN478",
    projectDescription: "",
    data: [
      {
        imageId: "ARAGO1",
        title: "BCN047 - ARAGÓ",
        year: 2021,
        location: "El Clot, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/011.Arago/Arago01.jpg"),
        isExtraSmallThumbnail: true,
        text: "When natural light comes in, all spots have a warm joy and sensation of spaciousness. Opening up the apartment space as much as possible is the project’s main intention, considering it as a unique space looking to the awesome views.",
      },
      {
        imageId: "ARAGO2",
        title: "BCN047 - ARAGÓ",
        year: 2021,
        location: "El Clot, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/011.Arago/Arago02.jpg"),
        isSpecialThumbnail: true,
        text: "",
      },
      {
        imageId: "ARAGO3",
        title: "BCN047 - ARAGÓ",
        year: 2021,
        location: "El Clot, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/011.Arago/Arago03.jpg"),
        isCroppedThumbnail: true,
        text: "The opening of a sliding door can create a game of visual diagonals, providing a fluent spatial relation in-between the apartment different areas and giving a wider perception of the apartment space.",
      },
      {
        imageId: "ARAGO4",
        title: "BCN047 - ARAGÓ",
        year: 2021,
        location: "El Clot, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/011.Arago/Arago04.jpg"),
        isSpecialPortrait: true,
        text: "",
      },
      {
        imageId: "ARAGO5",
        title: "BCN047 - ARAGÓ",
        year: 2021,
        location: "El Clot, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/011.Arago/Arago05.jpg"),
        isSpecialPortrait: true,
        text: "",
      },
      {
        imageId: "ARAGO6",
        title: "BCN047 - ARAGÓ",
        year: 2021,
        location: "El Clot, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/011.Arago/Arago06.jpg"),
        isSpecialLandscape: true,
        text: "",
      },
    ],
  },
  {
    projectId: "STCGT1",
    projectDescription: "",
    data: [
      {
        imageId: "STCGT1",
        title: "LFS18 - LA FLORESTA",
        year: 2020,
        location: "Sant Cugat",
        expedient: "456JIK",
        image: require("../public/photos/projects_architecture/08.SantCugat/SantCugat_1.jpg"),
        isLandscape: false,
        text: "The project located in the middle of the natural park of Collserola, in Sant Cugat, allows us to blur the border between the external environment and the interior of the house as much as possible. The sky, the vegetation, the light, etc. become the borders of the house.",
      },
      {
        imageId: "STCGT2",
        title: "LFS18 - LA FLORESTA",
        year: 2020,
        location: "Sant Cugat",
        expedient: "456JIK",
        image: require("../public/photos/projects_architecture/08.SantCugat/SantCugat_2.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "STCGT3",
        title: "LFS18 - LA FLORESTA",
        year: 2020,
        location: "Sant Cugat",
        expedient: "456JIK",
        image: require("../public/photos/projects_architecture/08.SantCugat/SantCugat_3.jpg"),
        isLandscape: true,
        text: "The shape and external appearance of this building is not coincidental. The collection of water, the procurement of clean energy, and the low-energy consumption of the house, etc. allow us to obtain more energy than we actually consume.",
      },
      {
        imageId: "STCGT4",
        title: "LFS18 - LA FLORESTA",
        year: 2020,
        location: "Sant Cugat",
        expedient: "456JIK",
        image: require("../public/photos/projects_architecture/08.SantCugat/SantCugat_4.jpg"),
        isLandscape: true,
        text: "",
      },
    ],
  },
  {
    projectId: "GLT1",
    projectDescription: "",
    data: [
      {
        imageId: "GLT2",
        title: "GUA2 - HOUSE GUALTA",
        year: 2019,
        location: "Gualta",
        expedient: "123JIK",
        image: require("../public/photos/projects_architecture/07.Gualta/Gualta_2.jpg"),
        isLandscape: true,
        text: "The consecution of box-like units as a basic housing element, which are provided and positioned so that each of these elements achieve their specific function. The link between each volume is developed in the most neutral and transparent way, providing spaces of transition and communication.",
      },
      {
        imageId: "GLT1",
        title: "GUA2 - HOUSE GUALTA",
        year: 2019,
        location: "Gualta",
        expedient: "123JIK",
        image: require("../public/photos/projects_architecture/07.Gualta/Gualta_1.jpg"),
        extraLandscape: true,
        text: "",
      },
      {
        imageId: "GLT3",
        title: "GUA2 - HOUSE GUALTA",
        year: 2019,
        location: "Gualta",
        expedient: "123JIK",
        image: require("../public/photos/projects_architecture/07.Gualta/Gualta_3.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "GLT4",
        title: "GUA2 - HOUSE GUALTA",
        year: 2019,
        location: "Gualta",
        expedient: "123JIK",
        image: require("../public/photos/projects_architecture/07.Gualta/Gualta_4.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "GLT5",
        title: "GUA2 - HOUSE GUALTA",
        year: 2019,
        location: "Gualta",
        expedient: "123JIK",
        image: require("../public/photos/projects_architecture/07.Gualta/Gualta_5.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "GLT6",
        title: "GUA2 - HOUSE GUALTA",
        year: 2019,
        location: "Gualta",
        expedient: "123JIK",
        image: require("../public/photos/projects_architecture/07.Gualta/Gualta_6.jpg"),
        isLandscape: true,
        text: "",
      },
    ],
  },
  {
    projectId: "PDG1",
    projectDescription: "",
    data: [
      {
        imageId: "PDG1",
        title: "BCN012 - GRÀCIA",
        year: 2019,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/01.PDG/PDG_1.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "PDG2",
        title: "BCN012 - GRÀCIA",
        year: 2019,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/01.PDG/PDG_2.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "PDG3",
        title: "BCN012 - GRÀCIA",
        year: 2019,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/01.PDG/PDG_3.jpg"),
        isLandscape: false,
        text: "Renovating this ground floor apartment in the Paseo de Gracia was a real challenge. We wanted to emphasize the inner courtyard as the central axis. What might seem to be the most negative aspect of the apartment, becomes the key to the project. The main greenery and the carefully designed lighting are key to give the apartment the atmosphere it requires.",
      },
      {
        imageId: "PDG4",
        title: "BCN012 - GRÀCIA",
        year: 2019,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/01.PDG/PDG_4.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "PDG5",
        title: "BCN012 - GRÀCIA",
        year: 2019,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/01.PDG/PDG_5.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "PDG6",
        title: "BCN012 - GRÀCIA",
        year: 2019,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/01.PDG/PDG_6.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "PDG7",
        title: "BCN012 - GRÀCIA",
        year: 2019,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/01.PDG/PDG_7.jpg"),
        isLandscape: false,
        text: "Working on a ground floor gives us clues on how to create a bridge between street life and the apartment. For this reason we created a social area, with the kitchen as the main axis, positioned at the front line of the main façade, in this way we can link the life of the street with the life of the apartment. A bench connects the interior space with the exterior in a much more intimate way.",
      },
      {
        imageId: "PDG8",
        title: "BCN012 - GRÀCIA",
        year: 2019,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/01.PDG/PDG_8.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "PDG9",
        title: "BCN012 - GRÀCIA",
        year: 2019,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/01.PDG/PDG_9.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "PDG10",
        title: "BCN012 - GRÀCIA",
        year: 2019,
        location: "Eixample, Barcelona",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/01.PDG/PDG_10.jpg"),
        isLandscape: false,
        text: "Households are appendices of the city itself. In fact, they are part of it. The social connection between both must be correct so that both the house and the street have the right elements, filters, barriers, etc. to interact in adequate measure and give life and light to each other mutually.",
      },
    ],
  },
  {
    projectId: "MLRC1",
    projectDescription: "",
    data: [
      {
        imageId: "MLRC1",
        title: "BCN023 - MALLORCA",
        year: 2018,
        location: "Eixample, Barcelona",
        expedient: "456ABC",
        image: require("../public/photos/projects_architecture/02.Mallorca/Mallorca_1.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "MLRC2",
        title: "BCN023 - MALLORCA",
        year: 2018,
        location: "Eixample, Barcelona",
        expedient: "456ABC",
        image: require("../public/photos/projects_architecture/02.Mallorca/Mallorca_2.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "MLRC3",
        title: "BCN023 - MALLORCA",
        year: 2018,
        location: "Eixample, Barcelona",
        expedient: "456ABC",
        image: require("../public/photos/projects_architecture/02.Mallorca/Mallorca_3.jpg"),
        isLandscape: false,
        text: "The spaces of a house must be well related to each other. Likewise, the flexibility that exists between them is key to the adaptation of its function in the day to day and above all in time. Families grow, evolve, etc. and architecture must be able to adapt to these changes.",
      },
      {
        imageId: "MLRC4",
        title: "BCN023 - MALLORCA",
        year: 2018,
        location: "Eixample, Barcelona",
        expedient: "456ABC",
        image: require("../public/photos/projects_architecture/02.Mallorca/Mallorca_4.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "MLRC5",
        title: "BCN023 - MALLORCA",
        year: 2018,
        location: "Eixample, Barcelona",
        expedient: "456ABC",
        image: require("../public/photos/projects_architecture/02.Mallorca/Mallorca_5.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "MLRC6",
        title: "BCN023 - MALLORCA",
        year: 2018,
        location: "Eixample, Barcelona",
        expedient: "456ABC",
        image: require("../public/photos/projects_architecture/02.Mallorca/Mallorca_6.jpg"),
        isLandscape: true,
        text: "When thinking about flexible spaces, with different potential uses, we can respond to certain needs that today may not be relevant, but will arise over time.",
      },
    ],
  },
  {
    projectId: "CRD1",
    projectDescription: "",
    data: [
      {
        imageId: "CRD1",
        title: "CRD6 - RUSTIC HOUSE",
        year: 2015,
        location: "La Cerdanya",
        expedient: "789ABC",
        image: require("../public/photos/projects_architecture/03.Cerdanya/Cerdanya_1.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "CRD2",
        title: "CRD6 - RUSTIC HOUSE",
        year: 2015,
        location: "La Cerdanya",
        expedient: "789ABC",
        image: require("../public/photos/projects_architecture/03.Cerdanya/Cerdanya_2.jpg"),
        isLandscape: false,
        text: "It is difficult to find a balance between the parts of a house and its use. But when the optimal point is found, the spaces flow and the people who inhabit them can improve their way of interacting with each other, either by participating in the space or by using it to escape, while others may simply want to contemplate it.",
      },
      {
        imageId: "CRD3",
        title: "CRD6 - RUSTIC HOUSE",
        year: 2015,
        location: "La Cerdanya",
        expedient: "789ABC",
        image: require("../public/photos/projects_architecture/03.Cerdanya/Cerdanya_3.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "CRD4",
        title: "CRD6 - RUSTIC HOUSE",
        year: 2015,
        location: "La Cerdanya",
        expedient: "789ABC",
        image: require("../public/photos/projects_architecture/03.Cerdanya/Cerdanya_4.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "CRD5",
        title: "CRD6 - RUSTIC HOUSE",
        year: 2015,
        location: "La Cerdanya",
        expedient: "789ABC",
        image: require("../public/photos/projects_architecture/03.Cerdanya/Cerdanya_5.jpg"),
        isLandscape: true,
        text: "Natural light helps us understand the space. It is equally important to interpret what kind of light the architecture requires and how it should play with the spaces.",
      },
      {
        imageId: "CRD6",
        title: "CRD6 - RUSTIC HOUSE",
        year: 2015,
        location: "La Cerdanya",
        expedient: "789ABC",
        image: require("../public/photos/projects_architecture/03.Cerdanya/Cerdanya_6.jpg"),
        isLandscape: false,
        text: "",
      },
    ],
  },
  {
    projectId: "VRI1",
    projectDescription: "",
    data: [
      {
        imageId: "VRI11",
        title: "BCN025 - LLANÇA",
        year: 2014,
        location: "Eixample, Barcelona",
        expedient: "123DEF",
        image: require("../public/photos/projects_architecture/BCN025_LLANCA/ES2_BCN025LLANCA (6).jpg"),
        isLandscape: true,
        text: "Natural light helps us to understand the space. It is equally important to interpret what kind of light the architecture requires and how it should play with the spaces. ",
      },
      {
        imageId: "VRI12",
        title: "BCN025 - LLANÇA",
        year: 2014,
        location: "Eixample, Barcelona",
        expedient: "123DEF",
        image: require("../public/photos/projects_architecture/BCN025_LLANCA/ES2_BCN025LLANCA (1).jpg"),
        isLandscape: true,
        text: "The purpose is to expand the space of the house, so that the kitchen is connected to the dining room and favor the entry of natural light. The reform also allows recovering some of the original flooring, plumbing and false ceilings.",
      },
      {
        imageId: "VRI13",
        title: "BCN025 - LLANÇA",
        year: 2014,
        location: "Eixample, Barcelona",
        expedient: "123DEF",
        image: require("../public/photos/projects_architecture/BCN025_LLANCA/ES2_BCN025LLANCA (2).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "VRI14",
        title: "BCN025 - LLANÇA",
        year: 2014,
        location: "Eixample, Barcelona",
        expedient: "123DEF",
        image: require("../public/photos/projects_architecture/BCN025_LLANCA/ES2_BCN025LLANCA (3).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "VRI16",
        title: "BCN025 - LLANÇA",
        year: 2014,
        location: "Eixample, Barcelona",
        expedient: "123DEF",
        image: require("../public/photos/projects_architecture/BCN025_LLANCA/ES2_BCN025LLANCA (4).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "VRI15",
        title: "BCN025 - LLANÇA",
        year: 2014,
        location: "Eixample, Barcelona",
        expedient: "123DEF",
        image: require("../public/photos/projects_architecture/BCN025_LLANCA/ES2_BCN025LLANCA (5).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "VRI1",
        title: "BCN025 - LLANÇA",
        year: 2014,
        location: "Eixample, Barcelona",
        expedient: "123DEF",
        image: require("../public/photos/projects_architecture/04.Varios/Varios_1.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "VRI2",
        title: "BCN025 - LLANÇA",
        year: 2019,
        location: "Unknown",
        expedient: "123DEF",
        image: require("../public/photos/projects_architecture/04.Varios/Varios_2.jpg"),
        isLandscape: false,
        text: "Noble materials, like wood, clay, stone, etc., not only have character, but also health benefits, as well as a completely natural aging. This makes the beauty of the materials sustainable over time and the spaces acquire more and more life as time goes by.",
      },
      {
        imageId: "VRI3",
        title: "BCN025 - LLANÇA",
        year: 2014,
        location: "Eixample, Barcelona",
        expedient: "123DEF",
        image: require("../public/photos/projects_architecture/04.Varios/Varios_3.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "VRI4",
        title: "BCN025 - LLANÇA",
        year: 2019,
        location: "Unknown",
        expedient: "123DEF",
        image: require("../public/photos/projects_architecture/04.Varios/Varios_4.jpg"),
        isLandscape: false,
        text: "",
      },
    ],
  },
  {
    projectId: "VLN1",
    projectDescription: "",
    data: [
      {
        imageId: "VLN1",
        title: "VLN29 - HOUSE LA BULLA",
        year: 2017,
        location: "Vilanova i la Geltrú",
        expedient: "456DEF",
        image: require("../public/photos/projects_architecture/05.Vilanova/Vilanova_1.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "VLN2",
        title: "VLN29 - HOUSE LA BULLA",
        year: 2017,
        location: "Vilanova i la Geltrú",
        expedient: "456DEF",
        image: require("../public/photos/projects_architecture/05.Vilanova/Vilanova_2.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "VLN3",
        title: "VLN29 - HOUSE LA BULLA",
        year: 2017,
        location: "Vilanova i la Geltrú",
        expedient: "456DEF",
        image: require("../public/photos/projects_architecture/05.Vilanova/Vilanova_3.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "VLN4",
        title: "VLN29 - HOUSE LA BULLA",
        year: 2017,
        location: "Vilanova i la Geltrú",
        expedient: "456DEF",
        image: require("../public/photos/projects_architecture/05.Vilanova/Vilanova_4.jpg"),
        isLandscape: true,
        text: "",
      },
    ],
  },
  {
    projectId: "STG1",
    projectDescription: "",
    data: [
      {
        imageId: "STG1",
        title: "SPR51 - HOUSE MAS ALBA",
        year: 2018,
        location: "Sitges",
        expedient: "789DEF",
        image: require("../public/photos/projects_architecture/06.Sitges/Sitges_1.jpg"),
        isLandscape: true,
        text: "The patio as an element of articulation is a concept that promotes the correct relationship between the interior spaces, while also relating to the outdoor space. This element allows us to regulate natural light, articulate spaces and allow ventilation. It is another indoor space without a roof.",
      },
      {
        imageId: "STG2",
        title: "SPR51 - HOUSE MAS ALBA",
        year: 2018,
        location: "Sitges",
        expedient: "789DEF",
        image: require("../public/photos/projects_architecture/06.Sitges/Sitges_2.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "STG3",
        title: "SPR51 - HOUSE MAS ALBA",
        year: 2018,
        location: "Sitges",
        expedient: "789DEF",
        image: require("../public/photos/projects_architecture/06.Sitges/Sitges_3.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "STG4",
        title: "SPR51 - HOUSE MAS ALBA",
        year: 2018,
        location: "Sitges",
        expedient: "789DEF",
        image: require("../public/photos/projects_architecture/06.Sitges/Sitges_4.jpg"),
        isLandscape: true,
        text: "",
      },
    ],
  },
  {
    projectId: "IDT1",
    projectDescription: "",
    data: [
      {
        imageId: "IDT11",
        title: "SOR7 - ALMAZAN",
        year: 2018,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/SOR7_ALMAZAN/E32-Almazan (2).jpg"),
        isLandscape: true,
        text: "The shape of the building marks the project itself From a very industrial environment, we can always see something beautiful and in harmony with the space. ",
      },
      {
        imageId: "IDT12",
        title: "SOR7 - ALMAZAN",
        year: 2018,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/SOR7_ALMAZAN/E32-Almazan (1).jpg"),
        isLandscape: true,
        text: "Also it is more aerodynamic, structurally the dimension is smaller and it has positive consequences. The project ends up having a formal, structural and aesthetic coherence as well.",
      },
      {
        imageId: "IDT13",
        title: "SOR7 - ALMAZAN",
        year: 2018,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/SOR7_ALMAZAN/E32-Almazan (3).jpg"),
        isLandscape: true,
        text: "The nave follows a rectangular floor plan with a parabola-shaped roof. In this way, the material that would normally be used is reduced by 30%, respecting the integration of the entire program in terms of design, research and the environment.",
      },
      {
        imageId: "IDT14",
        title: "SOR7 - ALMAZAN",
        year: 2018,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/SOR7_ALMAZAN/E32-Almazan (4).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "IDT15",
        title: "SOR7 - ALMAZAN",
        year: 2018,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/SOR7_ALMAZAN/E32-Almazan (5).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "IDT16",
        title: "SOR7 - ALMAZAN",
        year: 2018,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/SOR7_ALMAZAN/E32-Almazan (6).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "IDT17",
        title: "SOR7 - ALMAZAN",
        year: 2018,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_architecture/SOR7_ALMAZAN/E32-Almazan (7).jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "IDT1",
        title: "SOR7 - ALMAZAN",
        year: 2015,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_building/01.Industrial/industrial_1.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "IDT2",
        title: "SOR7 - ALMAZAN",
        year: 2015,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_building/01.Industrial/industrial_2.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "IDT3",
        title: "SOR7 - ALMAZAN",
        year: 2015,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_building/01.Industrial/industrial_3.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "IDT4",
        title: "SOR7 - ALMAZAN",
        year: 2015,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_building/01.Industrial/industrial_4.jpg"),
        isLandscape: false,
        text: "",
      },
      {
        imageId: "IDT5",
        title: "SOR7 - ALMAZAN",
        year: 2015,
        location: "Soria",
        expedient: "123ABC",
        image: require("../public/photos/projects_building/01.Industrial/industrial_5.jpg"),
        isLandscape: false,
        text: "",
      },
    ],
  },
  {
    projectId: "MGT1",
    projectDescription: "",
    data: [
      {
        imageId: "MGT1",
        title: "SOR8 - SMALL ALMAZAN",
        year: 2016,
        location: "Madrid",
        expedient: "123ABC",
        image: require("../public/photos/projects_building/02.Magatzem/Magatzem_1.jpg"),
        isLandscape: false,
        text: "Building for us implies applying the necessary knowledge to solve the project's challenges. This translates into testing materials, researching, generating prototypes, etc. in order to provide the most optimal solution and validate its execution.",
      },
      {
        imageId: "MGT2",
        title: "SOR8 - SMALL ALMAZAN",
        year: 2016,
        location: "Madrid",
        expedient: "123ABC",
        image: require("../public/photos/projects_building/02.Magatzem/Magatzem_2.jpg"),
        isLandscape: true,
        text: "",
      },
    ],
  },
  {
    projectId: "CRD11",
    projectDescription: "",
    data: [
      {
        imageId: "CRD11",
        title: "GIR3 - HOUSE URTX",
        year: 2019,
        location: "La Cerdanya",
        expedient: "123ABC",
        image: require("../public/photos/projects_building/03.Cerdanya2/Cerdanya_2_1.jpg"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "CRD2",
        title: "GIR3 - HOUSE URTX",
        year: 2019,
        location: "La Cerdanya",
        expedient: "123ABC",
        image: require("../public/photos/projects_building/03.Cerdanya2/Cerdanya_2_2.png"),
        isLandscape: true,
        text: "",
      },
      {
        imageId: "CRD3",
        title: "GIR3 - HOUSE URTX",
        year: 2019,
        location: "La Cerdanya",
        expedient: "123ABC",
        image: require("../public/photos/projects_building/03.Cerdanya2/Cerdanya_2_3.jpg"),
        isLandscape: true,
        text: "",
      },
    ],
  },
];

export default architecture_projects;
