const architecture_items = [
  {
    project_id: "BCN44",
    title: "BCN44 - HOUSE",
    year: 2022,
    location: "Sant Antoni de Vilamajor, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/BCN44/E32_BCN44HOUSE_1.png"),
    isWeirdLandscape: true,
    spaced: 0,
  },
  {
    project_id: "BCN44",
    title: "BCN44 - HOUSE",
    year: 2022,
    location: "Sant Antoni de Vilamajor, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/BCN44/E32_BCN44HOUSE_2.png"),
    isWeirdLandscape: true,
    spaced: 1,
  },  
  {
    project_id: "BDN07",
    title: "BDN07 - HOUSE",
    year: 2022,
    location: "Badalona, Spain",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/BDN07/E32_BDN07HOUSE_portada.png"),
    isLandscape: true,
    spaced: 0,
  },
  {
    project_id: "BDN07",
    title: "BDN07 - HOUSE",
    year: 2022,
    location: "Badalona, Spain",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/BDN07/E32_BDN07HOUSE_2.png"),
    isLandscape: true,
    spaced: 2,
  },
  {
    project_id: "CAB05",
    title: "CAB05 - HOUSE",
    year: 2022,
    location: "Cabrils, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/CAB05/E32_CAB05HOUSE_1.png"),
    isMidsizeLandscape: true,
    spaced: 0,
  },
  {
    project_id: "CAB05",
    title: "CAB05 - HOUSE",
    year: 2022,
    location: "Cabrils, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/CAB05/E32_CAB05HOUSE_2.png"),
    isSpecialLandscape: true,
    spaced: 2,
  },
  {
    project_id: "PRS292",
    title: "PRS292 - HOUSE",
    year: 2022,
    location: "Prats i Sansors, Lleida",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/PRS292/E32_PRS292HOUSE_2.png"),
    isSpecialLandscape: true,
    spaced: 0,
  },
  {
    project_id: "PRS292",
    title: "PRS292 - HOUSE",
    year: 2022,
    location: "Prats i Sansors, Lleida",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/PRS292/E32_PRS292HOUSE_3.png"),
    isSpecialLandscape: true,
    spaced: 2,
  },
  {
    project_id: "BCN017",
    title: "BCN017 - SANTS",
    year: 2021,
    location: "Sants-Montjuïc, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/09.Sants/Sants01.jpg"),
    isPortrait: true,
    spaced: 0,
  },
  {
    project_id: "BCN017",
    title: "BCN017 - SANTS",
    year: 2021,
    location: "Sants-Montjuïc, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/09.Sants/Sants02.jpg"),
    isSmallPortrait: true,
    spaced: 1,
  },
  {
    project_id: "BCN326",
    title: "BCN032 - PROVENÇA",
    year: 2021,
    location: "Eixample, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/010.Provenca/Provenca01.jpg"),
    isPortrait: true,
    spaced: 0,
  },
  {
    project_id: "BCN326",
    title: "BCN032 - PROVENÇA",
    year: 2021,
    location: "Eixample, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/010.Provenca/Provenca02.jpg"),
    isMediumLandscape: true,
    spaced: 2,
  },
  {
    project_id: "BCN478",
    title: "BCN047 - ARAGÓ",
    year: 2021,
    location: "El Clot, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/011.Arago/Arago01.jpg"),
    isLargePortrait: true,
    spaced: 0,
  },
  {
    project_id: "BCN478",
    title: "BCN047 - ARAGÓ",
    year: 2021,
    location: "El Clot, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/011.Arago/Arago02.jpg"),
    isMediumPortrait: true,
    spaced: 2,
  },
  {
    project_id: "STCGT1",
    title: "LFS18 - LA FLORESTA",
    year: 2020,
    location: "Sant Cugat",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/08.SantCugat/SantCugat_2.jpg"),
    isLandscape: true,
    spaced: 0,
  },
  {
    project_id: "STCGT1",
    title: "LFS18 - LA FLORESTA",
    year: 2020,
    location: "Sant Cugat",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/08.SantCugat/SantCugat_1.jpg"),
    isLandscape: false,
    spaced: 1,
  },
  {
    project_id: "GLT1",
    title: "GUA2 - HOUSE GUALTA",
    year: 2020,
    location: "Gualta, Empordà",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/07.Gualta/Destacada_Gualta.jpg"),
    isLandscape: false,
    spaced: 1,
  },
  {
    project_id: "PDG1",
    title: "BCN012 - GRÀCIA",
    year: 2019,
    location: "Eixample, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/01.PDG/PDG_4.jpg"),
    isLandscape: true,
    spaced: 0,
  },
  {
    project_id: "PDG1",
    title: "BCN012 - GRÀCIA",
    year: 2019,
    location: "Eixample, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/01.PDG/PDG_1.jpg"),
    isLandscape: false,
    spaced: 2,
  },
  {
    project_id: "MLRC1",
    title: "BCN023 - MALLORCA",
    year: 2018,
    location: "Eixample, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/02.Mallorca/Mallorca_1.jpg"),
    isLandscape: false,
    spaced: 0,
  },
  {
    project_id: "MLRC1",
    title: "BCN023 - MALLORCA",
    year: 2018,
    location: "Eixample, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/02.Mallorca/Mallorca_6.jpg"),
    isLandscape: true,
    spaced: 1,
  },
  {
    project_id: "CRD1",
    title: "CRD6 - RUSTIC HOUSE",
    year: 2015,
    location: "La Cerdanya",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/03.Cerdanya/Cerdanya_6.jpg"),
    isLandscape: false,
    spaced: 0,
  },
  {
    project_id: "CRD1",
    title: "CRD6 - RUSTIC HOUSE",
    year: 2015,
    location: "La Cerdanya",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/03.Cerdanya/Cerdanya_1.jpg"),
    isLandscape: false,
    spaced: 1,
  },
  {
    project_id: "VRI1",
    title: "BCN025 - LLANÇA",
    year: 2014,
    location: "Eixample, Barcelona",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/BCN025_LLANCA/E32_BCN025LLANCA_6.png"),
    isLandscape: true,
    spaced: 0,
  },
  {
    project_id: "VLN1",
    title: "VLN29 - HOUSE LA BULLA",
    year: 2017,
    location: "Vilanova i la Geltrú",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/05.Vilanova/Vilanova_3.jpg"),
    isLandscape: false,
    spaced: 1,
  },
  {
    project_id: "STG1",
    title: "SPR51 - HOUSE MAS ALBA",
    year: 2018,
    location: "Sitges",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/06.Sitges/Sitges_2.jpg"),
    isLandscape: false,
    spaced: 1,
  },
  {
    project_id: "IDT1",
    title: "SOR7 - ALMAZAN",
    year: 2018,
    location: "Soria",
    expedient: "123ABC",
    image: require("../public/photos/projects_architecture/SOR7_ALMAZAN/E32-Almazan_2.png"),
    isLandscape: true,
    spaced: 0,
  },
  {
    project_id: "IDT1",
    title: "SOR7 - ALMAZAN",
    year: 2015,
    location: "Soria",
    expedient: "123ABC",
    image: require("../public/photos/projects_building/01.Industrial/industrial_1.jpg"),
    isLandscape: true,
    spaced: 1,
  },
  {
    project_id: "MGT1",
    title: "SOR8 - SMALL ALMAZAN",
    year: 2016,
    location: "Madrid",
    expedient: "123ABC",
    image: require("../public/photos/projects_building/02.Magatzem/Magatzem_1.jpg"),
    isLandscape: false,
    spaced: 1,
  },
  {
    project_id: "CRD11",
    title: "GIR3 - HOUSE URTX",
    year: 2019,
    location: "La Cerdanya",
    expedient: "123ABC",
    image: require("../public/photos/projects_building/03.Cerdanya2/Cerdanya_2_3.jpg"),
    isLandscape: true,
    spaced: 2,
  },
];

export default architecture_items;
